### PR TITLE
Add Java 11 Travis build

### PR DESCRIPTION
**Pull request by szpak**
Updated also JaCoCo plugin for Java 11 compatibility.

Powered by PKP ;).

### CODE REVIEW

**Comment by szpak** [comment]
Would work better having Travis enabled :)
https://travis-ci.org/pivovarit/ThrowingFunction

image

**Comment by pivovarit** [comment]
@szpak it is enabled, it's just only I can see it :)
screenshot 2018-10-10 at 10 48 23

**Comment by szpak** [comment]
Strange, I though that Travis builds for the public projects are public.

**Comment by pivovarit** [comment]
Try [this](https://travis-ci.org/pivovarit/throwing-function/builds/439216526?utm_source=github_status&utm_medium=notification):

**Pull request merged**
